In [2]:
%load_ext autoreload
%autoreload 2

In [3]:
import pandas as pd
import numpy as np
import sys
sys.path.append('..')
import bets
import os
import glob
import datetime as dt
import time
#import ot
import json
import requests
import statsmodels.api as sm 
from tqdm import tqdm
pd.set_option('display.float_format', lambda x: '%.3f' % x)

nba = bets.nba()
import seaborn as sns
import matplotlib.pyplot as plt
import re
from warnings import simplefilter
simplefilter(action="ignore", category=pd.errors.PerformanceWarning)
from nba_api.stats.endpoints import BoxScoreAdvancedV3,leaguegamefinder,BoxScoreSummaryV2,LeagueDashOppPtShot,PlayerProfileV2,GameRotation,LeagueDashPlayerShotLocations

In [4]:
def runDay(date,toDb = False):
    data =  nba.threeData() #there will need to be an edit to only get data for today
    model = pd.read_pickle('data/model/thrLogit.pkl')
    #create model data and scale
    X = nba.cleanNaThr(data)
    X = nba.scaleData(X[X.game_date>'2024-03-01'].filter(model.params.index))
    idx = data[data.game_date==date].index
    #make day's predictions
    preds = model.predict(X.loc[idx])
    preds = preds.join(data[['name']])
    if toDb:
        try:
            nba.insert_data(preds,'preds')
        except:
            print('Data already in table')
    #create a data frame of the predictions
    #df = nba.probDf(preds.values,y.loc[valInd],data[['name','game_date']],valInd)
    
    #convert into odds
    c = [12,11,10,9,8,7,6,5,4,3,2,1,0]
    finalo = pd.DataFrame(np.array([nba.convertPercentToOdds(v) for r in preds[c].cumsum(axis=1).values for v in r]).reshape(preds[c].shape),
                         columns=c,index=preds.index)
    #finalu = pd.DataFrame(np.array([nba.convertPercentToOdds(v) for r in preds.cumsum(axis=1).values for v in r]).reshape(preds.shape),index=preds.index)
    overs = data[data.game_date==date][['name','team','game_id']].join(finalo.filter(preds.columns))
    #unders = data[data.game_date==date][['name','team','game_id']].join(finalu.filter(preds.columns))
    return overs,preds,model

### This notebook is to just run the current model and get our predictions

In [210]:
today = dt.datetime.today().strftime(format='%Y-%m-%d')
yst = (pd.to_datetime(today) + pd.to_timedelta(-1,unit='day')).strftime(format='%Y-%m-%d')
gids = nba.get_games(yst,yst)

In [211]:
yst

'2024-11-06'

In [212]:
nba.update_player_log([yst])
time.sleep(np.random.randint(5,15))
try:
    nba.update_shots_allowed([yst])
except:
    print('shots not updated yet')
time.sleep(np.random.randint(5,15))
nba.get_summary(gids.GAME_ID.unique())

started player logs at 07:02
getting first buckets : at 07:02

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 12/12 [00:32<00:00,  2.70s/it]

	completed at 07:03
started rebounds at 07:03
ended rebounds at 07:03
starting advanced box at 07:03

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 12/12 [00:56<00:00,  4.74s/it]

completed adv box at 07:04
start player shots at 07:04

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:06<00:00,  6.71s/it]

completed player shots at 07:04
plyrLogs has been updated with 262 rows

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:04<00:00,  4.25s/it]

Completed dribble data

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:09<00:00,  9.12s/it]

Completed spot data

  0%|                                                                                                                                     | 0/1 [00:01<?, ?it/s]

shots not updated yet

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 12/12 [00:08<00:00,  1.41it/s]

teamLog has been updated with 24 rows

In [213]:
over,preds,model = runDay(today,True)

In [214]:
def oddsData(today,tomorrow):
    '''ISO Formatted dates for today and tomorrow returns the games that will be played today ids for odds pulls
    Inputs: isoformatted dates for today and tomorrow
    Output: list of game ids
    '''
    eventURL = 'https://api.the-odds-api.com/v4/sports/basketball_nba/events?apiKey=153deeb03ca7b659e72d18e28219d1a8&dateFormat=iso&commenceTimeFrom={}&commenceTimeTo={}'.format(today,tomorrow)
    r = requests.get(eventURL)
    return [d['id'] for d in r.json()]

In [215]:
todayIso = (dt.datetime.now()).strftime('%Y-%m-%dT%H:%M:00Z')
tomor = (dt.datetime.now() + dt.timedelta(1)).strftime('%Y-%m-%dT%H:%M:00z')
events = oddsData(todayIso,tomor)

In [216]:
url = 'https://api.the-odds-api.com/v4/sports/basketball_nba/events/{}/odds?apiKey=153deeb03ca7b659e72d18e28219d1a8&regions=us&markets=player_threes,player_threes_alternate&dateFormat=iso&oddsFormat=american&bookmakers=draftkings%2Cfanduel%2Cespnbet'

In [217]:
df = pd.DataFrame()
for event in events:
    r = requests.get(url.format(event))
    game = r.json()
    for key in game.get('bookmakers'):
        bk = key.get('title')
        for mrkt in key.get('markets'):
            temp = pd.DataFrame(mrkt.get('outcomes'))
            temp.columns = ['over_under','name','price','threesMade']
            temp['book'] = bk
            temp['mrkt'] = mrkt
            df = pd.concat([temp,df])

In [218]:
odds = df.pivot_table(index=['name','threesMade','over_under'],columns=['book']).reset_index()

In [219]:
odds.columns = [col[1] if col[1]!= '' else col[0] for col in odds.columns]

In [220]:
#Name changes
odds.name = np.where(odds.name=='Herb Jones','Herbert Jones',odds.name)
odds.name = np.where(odds.name.str.contains('\.'),odds.name.str.replace('.',''),odds.name)
over.name = np.where(over.name.str.contains('\.'),over.name.str.replace('.',''),over.name)

In [221]:
over = over.melt(id_vars=['name','team','game_id'],var_name='threesMade')

In [222]:
over.threesMade = over.threesMade -.5

In [223]:
final = odds.merge(over[['name','team','threesMade','value']],how='left',on=['name','threesMade'])
final = final[final.over_under=='Over']

In [224]:
final['prob'] = np.where(final.value<0, abs(final.value) / (abs(final.value) + 100), 100/(final.value +100))

In [225]:
final['DKKelly'] = [nba.kellyCrit(p,odd) / 32 for p,odd in zip(final.prob,final.DraftKings)]
final['FanDuelKelly'] = [nba.kellyCrit(p,odd) / 32 for p,odd in zip(final.prob,final.FanDuel)]
final['espnKelly'] = [nba.kellyCrit(p,odd) / 32 for p,odd in zip(final.prob,final['ESPN BET'])]
final['dkBet'] = [x * 100 * 5 for x in final.DKKelly.values]
final['fdBet'] = [x * 100 * 5 for x in final.FanDuelKelly.values]
final['espnBet'] = [x * 100 * 5 for x in final.espnKelly]

In [1728]:
final.to_csv('{}.csv'.format(today))

In [205]:
preds[preds.name=='Grayson Allen'].iloc[:,3:-1].sum(axis=1)

53618   0.503
dtype: float64

In [206]:
p =  .531  * .478

In [207]:
nba.kellyCrit(p,842) / 32 * 100 *5

2.5812157808788596

In [248]:
p = .606  * .686 
nba.kellyCrit(p,522) / 32 * 5 * 100

4.74662811302682

In [247]:
final[final.team.isin(['MIN','SAS'])]

,name,threesMade,over_under,DraftKings,ESPN BET,FanDuel,team,value,prob,DKKelly,FanDuelKelly,espnKelly,dkBet,fdBet,espnBet
9,Anthony Edwards,0.500,Over,NaN,NaN,-7000.000,MIN,-4731.000,0.979,NaN,-0.015,NaN,NaN,-7.339,NaN
10,Anthony Edwards,1.500,Over,NaN,NaN,-700.000,MIN,-953.000,0.905,NaN,0.008,NaN,NaN,3.754,NaN
11,Anthony Edwards,2.500,Over,NaN,NaN,-220.000,MIN,-326.000,0.765,NaN,0.008,NaN,NaN,3.888,NaN
12,Anthony Edwards,3.500,Over,-110.000,-115.000,108.000,MIN,-127.000,0.559,0.002,0.005,0.002,1.170,2.368,0.826
14,Anthony Edwards,4.500,Over,NaN,NaN,240.000,MIN,245.000,0.290,NaN,-0.000,NaN,NaN,-0.094,NaN
15,Anthony Edwards,5.500,Over,NaN,NaN,500.000,MIN,554.000,0.153,NaN,-0.001,NaN,NaN,-0.258,NaN
16,Anthony Edwards,6.500,Over,NaN,NaN,1100.000,MIN,1436.000,0.065,NaN,-0.001,NaN,NaN,-0.311,NaN
17,Chris Paul,0.500,Over,-900.000,NaN,-650.000,SAS,-762.000,0.884,-0.005,0.004,NaN,-2.501,2.030,NaN
18,Chris Paul,1.500,Over,-191.500,-200.000,-149.500,SAS,-218.000,0.686,0.003,0.007,0.002,1.302,3.366,0.884
20,Chris Paul,2.500,Over,150.000,NaN,170.000,SAS,101.000,0.498,0.005,0.006,NaN,2.539,3.155,NaN
21,Chris Paul,3.500,Over,380.000,NaN,500.000,SAS,261.000,0.277,0.003,0.004,NaN,1.355,2.069,NaN
22,Chris Paul,4.500,Over,NaN,NaN,1300.000,SAS,657.000,0.132,NaN,0.002,NaN,NaN,1.021,NaN
33,Donte DiVincenzo,2.500,Over,120.000,120.000,NaN,MIN,-119.000,0.543,0.005,NaN,0.005,2.545,NaN,2.545
37,Harrison Barnes,0.500,Over,-250.000,-250.000,-260.000,SAS,-410.000,0.804,0.010,0.009,0.010,4.902,4.596,4.902
39,Harrison Barnes,1.500,Over,173.000,NaN,161.000,SAS,-132.000,0.569,0.010,0.009,NaN,4.997,4.707,NaN
41,Harrison Barnes,2.500,Over,550.000,NaN,500.000,SAS,157.000,0.389,0.009,0.008,NaN,4.344,4.171,NaN
42,Jaden McDaniels,1.500,Over,170.000,150.000,NaN,MIN,-154.000,0.606,0.012,NaN,0.011,5.855,NaN,5.372
53,Julian Champagnie,0.500,Over,-1000.000,NaN,-700.000,SAS,-907.000,0.901,-0.003,0.006,NaN,-1.443,3.212,NaN
54,Julian Champagnie,1.500,Over,-205.000,-200.000,-175.000,SAS,-295.000,0.747,0.007,0.009,0.008,3.560,4.747,3.758
56,Julian Champagnie,2.500,Over,145.000,NaN,159.000,SAS,-133.000,0.571,0.009,0.009,NaN,4.294,4.701,NaN
58,Julian Champagnie,3.500,Over,360.000,NaN,390.000,SAS,182.000,0.355,0.005,0.006,NaN,2.740,2.955,NaN
59,Julian Champagnie,4.500,Over,NaN,NaN,950.000,SAS,367.000,0.214,NaN,0.004,NaN,NaN,2.053,NaN
60,Julius Randle,0.500,Over,NaN,NaN,-360.000,MIN,-455.000,0.820,NaN,0.005,NaN,NaN,2.675,NaN
61,Julius Randle,1.500,Over,115.000,115.000,118.000,MIN,-118.000,0.541,0.004,0.005,0.004,2.225,2.383,2.225
63,Julius Randle,2.500,Over,NaN,NaN,360.000,MIN,201.000,0.332,NaN,0.005,NaN,NaN,2.293,NaN
64,Keldon Johnson,0.500,Over,-350.000,NaN,NaN,SAS,-617.000,0.861,0.012,NaN,NaN,5.819,NaN,NaN
65,Keldon Johnson,1.500,Over,127.500,125.000,NaN,SAS,-218.000,0.686,0.014,NaN,0.014,6.858,NaN,6.781
67,Keldon Johnson,2.500,Over,400.000,NaN,NaN,SAS,-109.000,0.522,0.013,NaN,NaN,6.280,NaN,NaN
75,Mike Conley,0.500,Over,-700.000,NaN,NaN,MIN,-841.000,0.894,0.005,NaN,NaN,2.341,NaN,NaN
76,Mike Conley,1.500,Over,-135.000,-160.000,NaN,MIN,-252.000,0.716,0.010,NaN,0.008,5.194,NaN,4.084
78,Mike Conley,2.500,Over,230.000,NaN,NaN,MIN,-111.000,0.526,0.010,NaN,NaN,5.000,NaN,NaN
79,Mike Conley,3.500,Over,650.000,NaN,NaN,MIN,173.000,0.366,0.008,NaN,NaN,4.200,NaN,NaN
80,Naz Reid,1.500,Over,NaN,-170.000,NaN,MIN,-159.000,0.614,NaN,NaN,-0.001,NaN,NaN,-0.664
82,Nickeil Alexander-Walker,1.500,Over,NaN,-130.000,NaN,MIN,-140.000,0.583,NaN,NaN,0.001,NaN,NaN,0.651
98,Victor Wembanyama,0.500,Over,-900.000,NaN,-750.000,SAS,-954.000,0.905,0.002,0.006,NaN,0.801,3.024,NaN
99,Victor Wembanyama,1.500,Over,-191.500,-200.000,-177.000,SAS,-335.000,0.770,0.010,0.011,0.010,5.154,5.675,4.849
101,Victor Wembanyama,2.500,Over,150.000,NaN,165.000,SAS,-166.000,0.624,0.012,0.012,NaN,5.835,6.191,NaN
102,Victor Wembanyama,3.500,Over,380.000,NaN,410.000,SAS,137.000,0.422,0.008,0.009,NaN,4.216,4.390,NaN
103,Victor Wembanyama,4.500,Over,NaN,NaN,1000.000,SAS,263.000,0.275,NaN,0.006,NaN,NaN,3.172,NaN

In [240]:
final[(final.fdBet>0) & (final.FanDuel.between(-200,300))].sort_values(by='fdBet',ascending=False).head(50)

,name,threesMade,over_under,DraftKings,ESPN BET,FanDuel,team,value,prob,DKKelly,FanDuelKelly,espnKelly,dkBet,fdBet,espnBet
101,Victor Wembanyama,2.500,Over,150.000,NaN,165.000,SAS,-166.000,0.624,0.012,0.012,NaN,5.835,6.191,NaN
99,Victor Wembanyama,1.500,Over,-191.500,-200.000,-177.000,SAS,-335.000,0.770,0.010,0.011,0.010,5.154,5.675,4.849
54,Julian Champagnie,1.500,Over,-205.000,-200.000,-175.000,SAS,-295.000,0.747,0.007,0.009,0.008,3.560,4.747,3.758
39,Harrison Barnes,1.500,Over,173.000,NaN,161.000,SAS,-132.000,0.569,0.010,0.009,NaN,4.997,4.707,NaN
56,Julian Champagnie,2.500,Over,145.000,NaN,159.000,SAS,-133.000,0.571,0.009,0.009,NaN,4.294,4.701,NaN
108,Zach LaVine,2.500,Over,-122.500,-110.000,-111.500,CHI,-176.000,0.638,0.006,0.007,0.007,3.029,3.651,3.736
18,Chris Paul,1.500,Over,-191.500,-200.000,-149.500,SAS,-218.000,0.686,0.003,0.007,0.002,1.302,3.366,0.884
85,Nikola Vucevic,1.500,Over,145.000,145.000,164.500,CHI,-104.000,0.510,0.005,0.007,0.005,2.683,3.310,2.683
20,Chris Paul,2.500,Over,150.000,NaN,170.000,SAS,101.000,0.498,0.005,0.006,NaN,2.539,3.155,NaN
61,Julius Randle,1.500,Over,115.000,115.000,118.000,MIN,-118.000,0.541,0.004,0.005,0.004,2.225,2.383,2.225
12,Anthony Edwards,3.500,Over,-110.000,-115.000,108.000,MIN,-127.000,0.559,0.002,0.005,0.002,1.170,2.368,0.826
46,Jerami Grant,2.500,Over,130.000,130.000,140.000,POR,-99.000,0.497,0.003,0.004,0.003,1.733,2.165,1.733
25,Coby White,2.500,Over,-127.500,-130.000,-122.500,CHI,-154.000,0.606,0.003,0.004,0.003,1.630,1.938,1.476
45,Jerami Grant,1.500,Over,-235.000,NaN,-195.000,POR,-232.000,0.699,-0.000,0.003,NaN,-0.141,1.741,NaN
110,Zach LaVine,3.500,Over,200.000,NaN,210.000,CHI,180.000,0.357,0.001,0.002,NaN,0.558,0.797,NaN

In [1706]:
p = .721 * .744

In [1707]:
nba.kellyCrit(p,249)* 100/32 * 7.5

8.208958584337351

In [1]:
final.sort_values(by='espnBet',ascending=False)

NameError: name 'final' is not defined

In [1636]:
.465 * .422 * .686

0.13461378000000002

In [1712]:
nba.kellyCrit(.639, -210) * 7.5 * 100 /32

-2.7914062499999996

In [1389]:
276/376

0.7340425531914894

In [1391]:
nba.kellyCrit(0.7340425531914894,-152) * 100 /32 * 5

5.152925531914894